Refactoring
siriak/MoneyManager pull request #60
Opened 2021-08-15 08:39 UTC by Adelhaide22

Add scroll saving, refactor business logic and display manager for winforms UI

2021-08-15 08:56 UTC, siriak requested changes

2021-08-15 08:56 UTC, siriak commented on Core.Tests/StateManagerTests.cs
> +        //[Test]
Uncomment and update tests

2021-08-15 08:56 UTC, siriak commented on Core/Categories/CategoriesOrderer.cs
> +            var typeToInt = new Dictionary<Type, int>
Make static readonly

2021-08-15 08:56 UTC, siriak commented on Core/Categories/CategoriesOrderer.cs
> +        public int Compare(Category x, Category y)
Add tests

2021-08-15 08:56 UTC, siriak commented on Core/IRepository.cs
> +        public void SaveAutoCategoriesToFile();
Why public?

2021-08-15 08:56 UTC, siriak commented on Core/IRepository.cs
> +        public void SaveAutoCategoriesToFile();
Why no parameters?

2021-08-15 08:56 UTC, siriak commented on Core/IRepository.cs
> +        public void SaveAutoCategoriesToFile();
Why ToFile in name?

2021-08-15 08:56 UTC, siriak commented on WinFormsUI/DisplayManager.cs
> +            var level = todayRelative switch
Move to BLL

2021-08-15 08:56 UTC, siriak commented on WinFormsUI/DisplayManager.cs
> +        public static string AddPrefixToCategory(double todayRelative, Category c)
GetPrefix(Level l)

2021-08-15 08:56 UTC, siriak commented on WinFormsUI/DisplayManager.cs
> +                _ when Equals(level, Levels.Empty) => "(EMPTY) ",
```suggestion
                Levels.Empty => "(EMPTY) ",
```

2021-08-15 08:56 UTC, siriak commented on WinFormsUI/TransactionEditor.Designer.cs
> +
Spaces

2021-08-15 08:56 UTC, siriak commented on WinFormsUI/TransactionEditor.cs
> +                btnSave_Clicked(null, null);
Move to Save method and call it from btnSave_Clicked and here

2021-09-04 09:26 UTC, Adelhaide22 commented on Core/IRepository.cs
> +        public void SaveAutoCategoriesToFile();
public - because it's used in another assembly (WinFormsUI)

2021-09-08 04:09 UTC, siriak approved these changes

2021-09-08 04:09 UTC, merged